services:
  frontend:
    image: nginx:alpine
    container_name: qr-url-analyzer_backend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    container_name: qr-url-analyzer_fronted
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
